name: Deploy Quizzes

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build site
        env:
          ANSWERS_BASE64: ${{ secrets.ANSWERS_BASE64 }}
        run: |
          echo "$ANSWERS_BASE64" | base64 --decode > .secret.answers.yaml
          deno run --allow-read --allow-write generate.js
          rm .secret.answers.yaml
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - id: deployment
        uses: actions/deploy-pages@v4
